# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from math import sqrt

val = "0"
result = "0"

class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.setWindowModality(QtCore.Qt.NonModal)
        Calculator.resize(287, 431)
        Calculator.setMinimumSize(QtCore.QSize(287, 431))
        Calculator.setMaximumSize(QtCore.QSize(287, 431))
        font = QtGui.QFont()
        font.setKerning(True)
        Calculator.setFont(font)
        Calculator.setStyleSheet("background-color: rgb(63, 63, 63);\n"
"color: white;")
        self.result = QtWidgets.QFrame(Calculator)
        self.result.setGeometry(QtCore.QRect(9, 19, 271, 51))
        self.result.setStyleSheet("background-color: rgb(74, 74, 74);\n"
"border-radius: 10px")
        self.result.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.result.setFrameShadow(QtWidgets.QFrame.Raised)
        self.result.setObjectName("result")
        self.main = QtWidgets.QLabel(self.result)
        self.main.setGeometry(QtCore.QRect(10, 5, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.main.setFont(font)
        self.main.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.main.setObjectName("main")
        self.ClearAllButton = QtWidgets.QPushButton(Calculator)
        self.ClearAllButton.setGeometry(QtCore.QRect(10, 80, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.ClearAllButton.setFont(font)
        self.ClearAllButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ClearAllButton.setStyleSheet("border: none;\n"
" background-color: rgb(74, 74, 74);\n"
"border-radius: 10px;")
        self.ClearAllButton.setObjectName("ClearAllButton")
        self.Procent = QtWidgets.QPushButton(Calculator)
        self.Procent.setGeometry(QtCore.QRect(80, 80, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Procent.setFont(font)
        self.Procent.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Procent.setStyleSheet("border: none;\n"
" background-color: rgb(74, 74, 74);\n"
"border-radius: 10px;")
        self.Procent.setObjectName("Procent")
        self.Mnozity = QtWidgets.QPushButton(Calculator)
        self.Mnozity.setGeometry(QtCore.QRect(150, 80, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Mnozity.setFont(font)
        self.Mnozity.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Mnozity.setStyleSheet("border: none;\n"
" background-color: rgb(74, 74, 74);\n"
"border-radius: 10px;")
        self.Mnozity.setObjectName("Mnozity")
        self.dility = QtWidgets.QPushButton(Calculator)
        self.dility.setGeometry(QtCore.QRect(220, 80, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.dility.setFont(font)
        self.dility.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dility.setStyleSheet("border: none;\n"
" background-color: rgb(74, 74, 74);\n"
"border-radius: 10px;")
        self.dility.setObjectName("dility")
        self.plus = QtWidgets.QPushButton(Calculator)
        self.plus.setGeometry(QtCore.QRect(220, 150, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.plus.setFont(font)
        self.plus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.plus.setStyleSheet("border: none;\n"
" background-color: rgb(74, 74, 74);\n"
"border-radius: 10px;")
        self.plus.setObjectName("plus")
        self.minus = QtWidgets.QPushButton(Calculator)
        self.minus.setGeometry(QtCore.QRect(220, 220, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.minus.setFont(font)
        self.minus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minus.setStyleSheet("border: none;\n"
" background-color: rgb(74, 74, 74);\n"
"border-radius: 10px;")
        self.minus.setObjectName("minus")
        self.dorivnie = QtWidgets.QPushButton(Calculator)
        self.dorivnie.setGeometry(QtCore.QRect(220, 360, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.dorivnie.setFont(font)
        self.dorivnie.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dorivnie.setStyleSheet("border: none;\n"
" background-color: rgb(74, 74, 74);\n"
"border-radius: 10px;")
        self.dorivnie.setObjectName("dorivnie")
        self.one = QtWidgets.QPushButton(Calculator)
        self.one.setGeometry(QtCore.QRect(10, 150, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.one.setFont(font)
        self.one.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.one.setStyleSheet("border: none;\n"
" background-color: rgb(74, 74, 74);\n"
"border-radius: 10px;")
        self.one.setObjectName("one")
        self.two = QtWidgets.QPushButton(Calculator)
        self.two.setGeometry(QtCore.QRect(80, 150, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.two.setFont(font)
        self.two.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.two.setStyleSheet("border: none;\n"
" background-color: rgb(74, 74, 74);\n"
"border-radius: 10px;")
        self.two.setObjectName("two")
        self.three = QtWidgets.QPushButton(Calculator)
        self.three.setGeometry(QtCore.QRect(150, 150, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.three.setFont(font)
        self.three.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.three.setStyleSheet("border: none;\n"
" background-color: rgb(74, 74, 74);\n"
"border-radius: 10px;")
        self.three.setObjectName("three")
        self.six = QtWidgets.QPushButton(Calculator)
        self.six.setGeometry(QtCore.QRect(150, 220, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.six.setFont(font)
        self.six.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.six.setStyleSheet("border: none;\n"
" background-color: rgb(74, 74, 74);\n"
"border-radius: 10px;")
        self.six.setObjectName("six")
        self.four = QtWidgets.QPushButton(Calculator)
        self.four.setGeometry(QtCore.QRect(10, 220, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.four.setFont(font)
        self.four.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.four.setStyleSheet("border: none;\n"
" background-color: rgb(74, 74, 74);\n"
"border-radius: 10px;")
        self.four.setObjectName("four")
        self.five = QtWidgets.QPushButton(Calculator)
        self.five.setGeometry(QtCore.QRect(80, 220, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.five.setFont(font)
        self.five.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.five.setStyleSheet("border: none;\n"
" background-color: rgb(74, 74, 74);\n"
"border-radius: 10px;")
        self.five.setObjectName("five")
        self.nine = QtWidgets.QPushButton(Calculator)
        self.nine.setGeometry(QtCore.QRect(150, 290, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.nine.setFont(font)
        self.nine.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.nine.setStyleSheet("border: none;\n"
" background-color: rgb(74, 74, 74);\n"
"border-radius: 10px;")
        self.nine.setObjectName("nine")
        self.seven = QtWidgets.QPushButton(Calculator)
        self.seven.setGeometry(QtCore.QRect(10, 290, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.seven.setFont(font)
        self.seven.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.seven.setStyleSheet("border: none;\n"
" background-color: rgb(74, 74, 74);\n"
"border-radius: 10px;")
        self.seven.setObjectName("seven")
        self.eigh = QtWidgets.QPushButton(Calculator)
        self.eigh.setGeometry(QtCore.QRect(80, 290, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.eigh.setFont(font)
        self.eigh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.eigh.setStyleSheet("border: none;\n"
" background-color: rgb(74, 74, 74);\n"
"border-radius: 10px;")
        self.eigh.setObjectName("eigh")
        self.noly = QtWidgets.QPushButton(Calculator)
        self.noly.setGeometry(QtCore.QRect(80, 360, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.noly.setFont(font)
        self.noly.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.noly.setStyleSheet("border: none;\n"
" background-color: rgb(74, 74, 74);\n"
"border-radius: 10px;")
        self.noly.setObjectName("noly")
        self.stepiny = QtWidgets.QPushButton(Calculator)
        self.stepiny.setGeometry(QtCore.QRect(220, 290, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.stepiny.setFont(font)
        self.stepiny.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.stepiny.setStyleSheet("border: none;\n"
" background-color: rgb(74, 74, 74);\n"
"border-radius: 10px;")
        self.stepiny.setObjectName("stepiny")
        self.koriny = QtWidgets.QPushButton(Calculator)
        self.koriny.setGeometry(QtCore.QRect(150, 360, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.koriny.setFont(font)
        self.koriny.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.koriny.setStyleSheet("border: none;\n"
" background-color: rgb(74, 74, 74);\n"
"border-radius: 10px;")
        self.koriny.setObjectName("koriny")
        self.cancel = QtWidgets.QPushButton(Calculator)
        self.cancel.setGeometry(QtCore.QRect(10, 360, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancel.setFont(font)
        self.cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel.setStyleSheet("border: none;\n"
" background-color: rgb(74, 74, 74);\n"
"border-radius: 10px;")
        self.cancel.setObjectName("cancel")

        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

        self.one.clicked.connect(lambda: self.add("1"))
        self.two.clicked.connect(lambda: self.add("2"))
        self.three.clicked.connect(lambda: self.add("3"))
        self.four.clicked.connect(lambda: self.add("4"))
        self.five.clicked.connect(lambda: self.add("5"))
        self.six.clicked.connect(lambda: self.add("6"))
        self.seven.clicked.connect(lambda: self.add("7"))
        self.eigh.clicked.connect(lambda: self.add("8"))
        self.nine.clicked.connect(lambda: self.add("9"))
        self.noly.clicked.connect(lambda: self.add("0"))
        self.Mnozity.clicked.connect(lambda: self.add("*"))
        self.dility.clicked.connect(lambda: self.add("/"))
        self.cancel.clicked.connect(lambda: self.add("backspace"))
        self.stepiny.clicked.connect(lambda: self.add("**"))
        self.plus.clicked.connect(lambda: self.add("+"))
        self.minus.clicked.connect(lambda: self.add("-"))
        self.koriny.clicked.connect(lambda: self.add("koriny"))
        self.Procent.clicked.connect(lambda: self.add("%"))
        self.ClearAllButton.clicked.connect(lambda: self.add("C"))
        self.dorivnie.clicked.connect(lambda: self.add("="))


    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "Calculator"))
        self.main.setText(_translate("Calculator", "0"))
        self.ClearAllButton.setText(_translate("Calculator", "C"))
        self.Procent.setText(_translate("Calculator", "%"))
        self.Mnozity.setText(_translate("Calculator", "*"))
        self.dility.setText(_translate("Calculator", "/"))
        self.plus.setText(_translate("Calculator", "+"))
        self.minus.setText(_translate("Calculator", "-"))
        self.dorivnie.setText(_translate("Calculator", "="))
        self.one.setText(_translate("Calculator", "1"))
        self.two.setText(_translate("Calculator", "2"))
        self.three.setText(_translate("Calculator", "3"))
        self.six.setText(_translate("Calculator", "6"))
        self.four.setText(_translate("Calculator", "4"))
        self.five.setText(_translate("Calculator", "5"))
        self.nine.setText(_translate("Calculator", "9"))
        self.seven.setText(_translate("Calculator", "7"))
        self.eigh.setText(_translate("Calculator", "8"))
        self.noly.setText(_translate("Calculator", "0"))
        self.stepiny.setText(_translate("Calculator", "**"))
        self.koriny.setText(_translate("Calculator", "√"))
        self.cancel.setText(_translate("Calculator", "backspace"))

    def add(self, value):
        global result, val
        _translate = QtCore.QCoreApplication.translate
        try:
            if value == '=':
                result = f"{eval(val)}"
                val = ""
                self.main.setText(_translate("Calculator", result))
            elif value == "C":
                val = ""
                result = "0"
                self.main.setText(_translate("Calculator", result))
            elif value == "backspace":
                val = val[:-1] if len(val) > 1 else "0"
                result = val
                self.main.setText(_translate("Calculator", result))
            elif value == "koriny":
                result = f"{sqrt(eval(val))}"
                val = ""
                self.main.setText(_translate("Calculator", result))
            else:
                if val == "0":  # щоб не було "01", "02"
                    val = value
                else:
                    val += value
                result = val
                self.main.setText(_translate("Calculator", result))
        except:
            result = "error"
            val = ""
            self.main.setText(_translate("Calculator", result))
            


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculator = QtWidgets.QDialog()
    ui = Ui_Calculator()
    ui.setupUi(Calculator)
    Calculator.show()
    sys.exit(app.exec_())
